[package]
name = "tw-runtime"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
timely = { workspace = true }
differential-dataflow = { workspace = true }
tw-core = { path = "../core" }

